### ISSUE TITLE
Saving refreshToken

### ISSUE THREAD

**Issue by deanpeterson** [spring-social/spring-social-google#21]
I had to override the buildAuthorizeUrl of the OAuth2Template class inside GoogleOAuth2Template to add a request for the Google refreshToken.  That works fine.  However, once the refresh token is used, the refreshToken is changed to null by the framework; after calling connection.refresh(), the refreshToken value is wiped out and there is no way to manually update the Connection object with the old reusable refreshToken before calling connectionRepository.updateConnection(connection). I want to be able to update the connection in the userconnection table to retain the old refreshToken. Is there an easy way to populate the refreshToken field without having to write extra database code to do it? Preferably I would have liked to just call a public setter method on the Connection object.

**Comment by aqtcole** [comment]
@GabiAxel I think the problem isn't really covered by those bugs. Rather it's caused in spring-social-core here:

https://github.com/spring-projects/spring-social/blob/master/spring-social-core/src/main/java/org/springframework/social/connect/support/OAuth2Connection.java#L103

The refresh method uses null for the additional parameters and the interceptor framework is bypassed so you can't modify the parameters to provide `access_type = offline`, which would make Google return a refresh token. Then initAccessTokens() overwrites refreshToken with null.
