### ISSUE TITLE
NullPointerException: No authentication header information while using Google API

### ISSUE THREAD

**Issue by jteso** [spring-social/spring-social-google#7]
**Description**
Intended to import all the google contacts associated with an authenticated user. 
As I cannot see any support on the API provided for this functionality (the instructions of your website -- http://www.gabiaxel.com/2011/09/spring-social-meets-google-apis.html--  may be based on an old version as the class 'GoogleOperations' is missing). I decided to use the google contact api via the method 'applyAuthentication', as follows:

The following code is executed after user is authenticated (application is a clone of this repository):

``` java
ContactsService contactsService = new ContactsService("my application");
google.applyAuthentication(contactsService);
URL feedUrl = feedUrl = new URL("https://www.google.com/m8/feeds/contacts/default/full");
ContactFeed resultFeed = resultFeed = contactsService.getFeed(feedUrl, ContactFeed.class); <-- Line causing the error
for (ContactEntry entry : resultFeed.getEntries()) {
     String fullName = entry.getName().getFullName().getValue();
     String email = null;
     for(Object e : entry.getEmailAddresses()) 
```

**Resulting in the following exception**

```
java.lang.NullPointerException: No authentication header information
    com.google.gdata.util.AuthenticationException.initFromAuthHeader(AuthenticationException.java:96)
    com.google.gdata.util.AuthenticationException.<init>(AuthenticationException.java:67)
    com.google.gdata.client.http.HttpGDataRequest.handleErrorResponse(HttpGDataRequest.java:596)
    com.google.gdata.client.http.GoogleGDataRequest.handleErrorResponse(GoogleGDataRequest.java:563)
    com.google.gdata.client.http.HttpGDataRequest.checkResponse(HttpGDataRequest.java:550)
    com.google.gdata.client.http.HttpGDataRequest.execute(HttpGDataRequest.java:530)
    com.google.gdata.client.http.GoogleGDataRequest.execute(GoogleGDataRequest.java:535)
    com.google.gdata.client.Service.getFeed(Service.java:1135)
    com.google.gdata.client.Service.getFeed(Service.java:998)
```

any idea how to fix this? Ideally i would like to use your library for the whole task ie. import all the contacts without using the gdata dependency, but as I said above, I dont see any method for it.

Thanks

**Comment by Rutvikmac** [comment]
String accessToken = args[0];
            Log.d("Accesstocken", accessToken);
           // String refresh = .getString("refresh_token");
            ContactsService contactsService = new ContactsService(
                    Constants.APP);
            contactsService.getRequestFactory().setHeader("User-Agent", Constants.APP);
       //     contactsService.setOAuth2Credentials(credential);
            contactsService.setHeader("Authorization", "Bearer " + accessToken);
            contactsService.setHeader("GData-Version", "3.0");

          //  contactsService.useSsl();
          //  googleCredential.refreshToken();
           //   contactsService.setUserCredentials("ankurmac21@gmail.com", "");
            List<ContactEntry> contactEntries = null;
            try {
                URL feedUrl = new URL(Constants.CONTACTS_URL);

                ContactFeed resultFeed = contactsService.getFeed(feedUrl,
                        ContactFeed.class);

                contactEntries = resultFeed.getEntries();


i got setheader null pointer exception ....any idea ?
